/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 15:17:57 GMT 2024
 */

package com.sleekbyte.tailor.common;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sleekbyte.tailor.common.RuleCategory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RuleCategory_ESTest extends RuleCategory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RuleCategory[] ruleCategoryArray0 = RuleCategory.values();
      assertEquals(8, ruleCategoryArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RuleCategory ruleCategory0 = RuleCategory.valueOf("CLARITY");
      assertEquals("Clarity", ruleCategory0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RuleCategory ruleCategory0 = RuleCategory.STYLE;
      String string0 = ruleCategory0.toString();
      assertEquals("Style", string0);
  }
}
