/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 10 01:16:26 GMT 2024
 */

package com.sleekbyte.tailor.common;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sleekbyte.tailor.common.ColorSettings;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ColorSettings_ESTest extends ColorSettings_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ColorSettings colorSettings0 = new ColorSettings(false, false);
      assertFalse(colorSettings0.colorOutput);
      assertFalse(colorSettings0.invertColor);
  }
}
